/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2021-05-12 04:28:43 
*/
export interface sports {
    soccer: string;
    basketball: string;
    golf: string;
}
